#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../.. T_A=vxWorks-ppc32sf-debug  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../.. T_A=vxWorks-ppc32sf-debug  $@

force:  ;
